[project]
name = "holonomy"
version = "0.1.0"
description = "Generating and solving holonomy puzzles"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "numpy~=2.0",
    "plotly",
    "ruff>=0.11.2",
]

[project.scripts]
holonomy = "holonomy:main"

[build-system]
requires = ["flit-core>=3.4,<4"]
build-backend = "flit_core.buildapi"
